github:[aidlearning] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: python/js # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: http://www.aidlearning.net# Replace with a single custom sponsorship URL
